server:
  port: 8090

spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
    ai:
      mcp:
        server:
          name: mcp-server
          version: 1.0.0
          type: SYNC
          see-message-endpoint: /mcp/message